<a href="https://colab.research.google.com/github/edinsonescobarunal/EdinsonUnal/blob/main/Borrador_de_proyecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Informe final IO I 2023-01

Diligencia las casillas indicadas.

**No modifique la estructura del archivo.**

Plantee y resuelva el problema utilizando [CVXPY](https://www.cvxpy.org/).

El código debe ser legible e incluir comentarios. Se recomienda utilizar la guía [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/).

# Integrantes del equipo que participaron en la elaboración del informe

Escriba, a continuación, los nombres y los apellidos de las personas que hayan **participado de manera significativa** en la elaboración del informe.

1.Sebastian Calero Angulo   
2.Ever José Teherán Herrera   
3.Edinson Alexander Escobar Matamba 

# Objetivo del proyecto

¿Qué van a minimizar o qué van a maximizar y en qué unidades se mide?

Maximizar el turismo de Italia y Francia entre sí durante 5 días en semana santa (miércoles, jueves, viernes, sábado y domingo) debido a que es un tiempo en el que muchas personas viajan a distintos destinos. 



# Importante:
Los conjuntos de datos correspondientes a coeficientes de costos, coeficientes técnicos y restricciones deben ser leídos desde urls.

Sugerencia: suba los datasets a Googledrive y luego publíquelos como página web. El siguiente enlace le indica cómo hacerlo: [Cómo publicar archivos de Documentos, Hojas de cálculo, Presentaciones y Formularios de Google](https://support.google.com/docs/answer/183965?hl=es-419&co=GENIE.Platform%3DDesktop).

Nota: si lo desea puede utilizar otro método para obtener las urls de los conjuntos de datos.

# Preparación del ejercicio

In [ ]:
# Escriba acá el código para importar las librerías requeridas
import cvxpy as cvx
import numpy as np
import pandas as pd



# Variables de decisión
¿Cuáles son las variables de decisión y cuáles son sus unidades de medida?

X_fim1: Personas que viajan de Francia a Italia el miércoles y alquilan para 1 día

X_fim2 : Personas que viajan de Francia a Italia el miércoles y alquilan para 2 días 

X_fim3 : Personas que viajan de Francia a Italia el miércoles y alquilan para 3 días

X_fim4 : Personas que viajan de Francia a Italia el miércoles y alquilan para 4 días 

X_fim5 : Personas que viajan de Francia a Italia el miércoles y alquilan para 5 días

X_fij1 : Personas que viajan de Francia a Italia el jueves y alquilan para 1 día 

X_fij2 : Personas que viajan de Francia a Italia el jueves y alquilan para 2 días

X_fij3 : Personas que viajan de Francia a Italia el jueves y alquilan para 3 días 

X_fij4 : Personas que viajan de Francia a Italia el jueves y alquilan para 4 días

X_fiv1 : Personas que viajan de Francia a Italia el viernes y alquilan para 1 día

X_fiv2 : Personas que viajan de Francia a Italia el viernes y alquilan para 2 días 

X_fiv3 : Personas que viajan de Francia a Italia el viernes y alquilan para 3 días 

X_fis1 : Personas que viajan de Francia a Italia el sábado y alquilan para 1 día

X_fis2 : Personas que viajan de Francia a Italia el sábado y alquilan para 2 días

X_fid1 : Personas que viajan de Francia a Italia el domingo y alquilan para 1 día

X_ifm1 Personas que viajan de Italia a Francia el miércoles y alquilan para 1 día 

X_ifm2 : Personas que viajan de Italia a Francia el miércoles y alquilan para 2 días 

X_ifm3 : Personas que viajan de Italia a Francia el miércoles y alquilan para 3 días

X_ifm4 : Personas que viajan de Italia a Francia el miércoles y alquilan para 4 días 

X_ifm5 : Personas que viajan de Italia a Francia el miércoles y alquilan para 5 días

X_ifj1 : Personas que viajan de Italia a Francia el jueves y alquilan para 1 día 

X_ifj2 : Personas que viajan de Italia a Francia el jueves y alquilan para 2 días

X_ifj3 : Personas que viajan de Italia a Francia el jueves y alquilan para 3 días 

X_ifj4 : Personas que viajan de Italia a Francia el jueves y alquilan para 4 días

X_ifv1 : Personas que viajan de Italia a Francia el viernes y alquilan para 1 día

X_ifv2 : Personas que viajan de Italia a Francia el viernes y alquilan para 2 días 

X_ifv3 : Personas que viajan de Italia a Francia el viernes y alquilan para 3 días  

X_ifs1 : Personas que viajan de Italia a Francia el sábado y alquilan para 1 día

X_ifs2 : Personas que viajan de Italia a Francia el sábado y alquilan para 2 días

X_ifd1: Personas que viajan de Italia a Francia el domingo y alquilan para 1 día

Unidad de medida: Número de personas 




In [ ]:
# Código para crear las variables de decisión
arr_pers_x = cvx.Variable((30,1))


# Coeficientes de costos

¿Cuáles son los coeficientes de costos y cuáles sus unidades de medida?

Los coeficientes de costos para nuestro problema son 1 

In [ ]:
# Código para cargar los coeficientes de costos
arr_pers_c = cvx.Parameter((30,1))

# ruta de los coeficientes de costos  
ruta = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS25mFQ9MXMPbybULpLBuTSlYBe42Vap_ZGq6pdBbnxrtgMY3COj0yuNmtQVBtlxSQW_MBKCzBow-eV/pub?output=csv"

# Carga del conjunto de datos a partir de la ruta 
arr_pers_c = np.loadtxt(ruta, delimiter=",", dtype=float)

# Imprimir los coeficientes de costos 
print("Los coeficientes de costos son: \n", arr_pers_c, "\n")


Los coeficientes de costos son: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.] 



# Función objetivo

In [ ]:
# Código para crear la función objetivo 
obj_turismo = cvx.Maximize(arr_pers_c @ arr_pers_x)


# Coeficientes técnicos

Los coeficientes tecnicos para nuestro problema son 1 (Para las variables que aparecen en las restricciones), -1(Para las restricciones de no negatividad) y 0(Para las variables que no aparecen en las restricciones). 

Unidad de medida de los coeficientes tecnicos de las restricciones camas/personas

### Escriba acá los coeficientes técnicos con sus correspondientes unidades de medida


In [ ]:
# Código para cargar los coeficientes técnicos
arr_pers_A = cvx.Parameter((40,30))

# Ruta de los coeficientes tecnicos
ruta_1 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSpLmvv_19sgBu9YnwOiBOqnccmaMSocINbVL9VM0klkieamP3hCF67QQY7XArMJBuvAjn-SNZLICvS/pub?output=csv"

# Carga del conjunto de datos a partir de la ruta de los coeficientes tecnicos
arr_pers_A = np.loadtxt(ruta_1, delimiter=",", dtype=float)

# Imprimir coeficientes tecnicos
print("Los coeficientes técnicos son: \n", arr_pers_A, "\n")




Los coeficientes técnicos son: 
 [[ 1.  1.  1. ...  0.  0.  0.]
 [ 0.  1.  1. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -1.  0.  0.]
 [ 0.  0.  0. ...  0. -1.  0.]
 [ 0.  0.  0. ...  0.  0. -1.]] 



# Restricciones

¿Cuáles son las restricciones y cuáles son sus unidades de medida?

NOTA: 
Los coeficientes técnicos para todas las restricciones son 1 y su unidad de medida es camas/personas. 
Las camas ofrecidas anualmente en Francia son 5.058.665 y en Italia 5.120.175 (El lado derecho en cada restricción se obtienen dividiendo el numero total de camas ofrecidas anualmente entre 365 para saber cuantas camas se ofrecen diariamente) 
De acuerdo al punto anterior para Italia: 5.120.175/365=14027,9 y para Francia: 5.058.665/365=13859,4

Restricción del miércoles en Italia: Las personas que viajan de Francia a Italia el miércoles deben ser menor o igual al número total de hospedajes por día de Italia. Así queda la restricción:
X_fim1 + X_fim2 + X_fim3 + X_fim4 + X_fim5 <= 14027
(Se mide en número de camas)

Restricción del jueves en Italia: Las personas que viajan de Francia a Italia el jueves más las personas que viajan el miércoles y se quedan 2, 3, 4 o 5 días deben ser menor o igual a el número total de hospedajes por día de Italia. Así queda la restricción: 
 (X_fij1 + X_fij2 + X_fij3 + X_fij4) + ( X_fim2 + X_fim3 + X_fim4 + X_fim5) <= 14027
(Se mide en número de camas)

Restricción del viernes en Italia: Las personas que viajan de Francia a Italia el sábado más las personas que viajan el miércoles y se quedan 3, 4 o 5 días y las personas que viajan el jueves y se quedan 2, 3 o 4 deben ser menor o igual a el número total de hospedajes por día de Italia. Así queda la restricción:
(X_fiv1 + X_fiv2 + X_fiv3 ) + (X_fim3 + X_fim4 + X_fim5) + (X_fij2 + X_fij3 + X_fij4) <= 14027
(Se mide en número de camas)

Restricción del sábado en Italia: Las personas que viajan de Francia a Italia el sábado más las personas que viajan el miércoles y se quedan 4 o 5 días, las personas que viajan el jueves y se quedan 3 o 4 y las personas que viajan el viernes y se quedan 2 o 3 deben ser menor o igual a el número total de hospedajes por día de Italia. Así queda la restricción:
(X_fis1 + X_fis2) + (X_fim4 + X_fim5) + (X_fij3 + X_fij4) + (X_fiv2 + X_fiv3) <= 14027
(Se mide en número de camas)

Restricción del domingo en Italia: Las personas que viajan de Francia a Italia el domingo más las personas que viajan el miércoles y se quedan 5 días, las personas que viajan el jueves y se quedan 4, las personas que viajan el viernes y se queda 3 y las personas que viajan el sábado y se quedan 2 deben ser menor o igual a el número total de hospedajes por día de Italia. Así queda la restricción:
(X_fid1) + (X_fim5) + (X_fij4) + (X_fiv3) + (X_fis2) <= 13859
(Se mide en número de camas)

Restricción del miércoles en Francia: Las personas que viajan de Italia a Francia el miércoles deben ser menor o igual al número total de hospedajes de Francia por día. Así queda la restricción:
 X_ifm1 + X_ifm2 + X_ifm3 + X_ifm4 + X_ifm5 <= 13859
(Se mide en número de camas)

Restricción del jueves en Francia: Las personas que viajan de Italia a Francia el jueves más las personas que viajan el miércoles y se quedan 2, 3, 4 o 5 días deben ser menor o igual a el número total de hospedajes por día en Francia. Así queda la restricción:
(X_ifj1 + X_ifj2 + X_ifj3 + X_ifj4) + ( X_ifm2 + X_ifm3 + X_ifm4 + X_ifm5) <= 13859
(Se mide en número de camas)

Restricción del viernes en Francia: Las personas que viajan de Italia a Francia el viernes más las personas que viajan el miércoles y se quedan 3, 4 o 5 días y las personas que viajan el jueves y se quedan 2, 3 o 4 deben ser menor o igual a el número total de hospedajes por día de Francia. Así queda la restricción:
( X_ifv1 + X_ifv2 + X_ifv3) + (X_ifm3 + X_ifm4 + X_ifm5) + (+ X_ifj2 + X_ifj3 + X_ifj4) <= 13859
(Se mide en número de camas)

Restricción del sábado en Francia: Las personas que viajan de Italia a Francia el sábado más las personas que viajan el miércoles y se quedan 4 o 5 días, las personas que viajan el jueves y se quedan 3 o 4 y las personas que viajan el viernes y se quedan 2 o 3 deben ser menor o igual a el número total de hospedajes por día de Francia. Así queda la restricción:
(X_ifs1 + X_ifs2) + (X_ifm4 + X_ifm5) + (X_ifj3 + X_ifj4) + (X_ifv2 + X_ifv3) <= 13859
(Se mide en número de camas)

Restricción del domingo en Francia: Las personas que viajan de Italia a Francia el domingo más las personas que viajan el miércoles y se quedan 5 días, las personas que viajan el jueves y se quedan 4, las personas que viajan el viernes y se queda 3 y las personas que viajan en el sábado y se quedan 2 deben ser menor o igual a el número total de hospedajes por día de Francia. Así queda la restricción:
( X_ifd1) + (X_ifm5) + (X_ifj4) + (X_ifv3) + (X_ifs2) <= 13859
(Se mide en número de camas)

Otras restricciones (no negatividad, enteros, binarios) 
Restricciones no negatividad 
X_fim1 , X_fim2 , X_fim3 , X_fim4 , X_fim5 , X_fij1 , X_fij2 , X_fij3 , X_fij4 , X_fiv1 , X_fiv2 , X_fiv3 , X_fis1 , X_fis2 , X_fid1 , X_ifm1 , X_ifm2 , X_ifm3 , X_ifm4 , X_ifm5 , X_ifj1 , X_ifj2 , X_ifj3 , X_ifj4 , X_ifv1 , X_ifv2 , X_ifv3 , X_ifs1 , X_ifs2 , X_ifd1 >= 0


In [ ]:
# Código para cargar las restricciones
arr_pers_b = cvx.Parameter((40,1))

# Ruta de las restricciones o limites de cama por día 
ruta_2 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ55C9H_m9UVazqpfJAUEXdLzjj3_b3zfGQWjVj4JrQEpX78i7rHuntMMjEBXnpIhCOj0leKYDKcULN/pub?output=csv"

# Carga del conjunto de datos a partir de la ruta de restricciones
arr_pers_b= np.loadtxt(ruta_2, delimiter=",", dtype=float).reshape((40,1))

# Imprimir el limite de camas por día en cada país
print("Las restricciones son: \n", arr_pers_b, "\n")


Las restricciones son: 
 [[14027.]
 [14027.]
 [14027.]
 [14027.]
 [14027.]
 [13859.]
 [13859.]
 [13859.]
 [13859.]
 [13859.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]] 



In [ ]:
# Código para plantear inecuaciones de las restricciones
arr_restricciones_día = [arr_pers_A @ arr_pers_x <= arr_pers_b]


# Estructuración del problema

In [ ]:
#Código para estructurar el problema
prob_turismo_pers = cvx.Problem(obj_turismo, arr_restricciones_día)


# Solución del problema

In [ ]:
# Código para solucionar el problema
prob_turismo_pers.solve() 
#Imprimir el estado de la solucion 
print("Estado de la solución matricial:", prob_turismo_pers.status)


Estado de la solución matricial: optimal


# Resultados

Muestre el valor óptimo de la función objetivo y los valores óptimos de las variables de decisión, junto con sus unidades.

In [ ]:
# Código para mostrar los resultados
print("Valor óptimo de la función objetivo matricial:", int(prob_turismo_pers.value))

print("Valores óptimos de las variables de decisión matricial:", 
      int(arr_pers_x[0].value), int(arr_pers_x[1].value), 
      int(arr_pers_x[2].value), int(arr_pers_x[3].value), int(arr_pers_x[4].value), 
      int(arr_pers_x[5].value), int(arr_pers_x[6].value), int(arr_pers_x[7].value), 
      int(arr_pers_x[8].value), int(arr_pers_x[9].value), int(arr_pers_x[10].value), 
      int(arr_pers_x[11].value), int(arr_pers_x[12].value), int(arr_pers_x[13].value), 
      int(arr_pers_x[14].value), int(arr_pers_x[15].value), int(arr_pers_x[16].value), 
      int(arr_pers_x[17].value), int(arr_pers_x[18].value), int(arr_pers_x[19].value), 
      int(arr_pers_x[20].value), int(arr_pers_x[21].value), int(arr_pers_x[22].value),
      int(arr_pers_x[23].value), int(arr_pers_x[24].value), int(arr_pers_x[25].value),
      int(arr_pers_x[26].value), int(arr_pers_x[27].value), int(arr_pers_x[28].value), 
      int(arr_pers_x[29].value),"\n")



Valor óptimo de la función objetivo matricial: 139429
Valores óptimos de las variables de decisión matricial: 14026 0 0 0 0 14026 0 0 0 14026 0 0 14026 0 14026 13858 0 0 0 0 13858 0 0 0 13858 0 0 13858 0 13858 



# Análisis de los resultados


A partir de los resultados se puede concluir que el problema del turismo que se planteó entre Francia e Italia para 5 días obtendrá su valor optimo de 139.429 personas si: 

Las personas que viajan de francia a Italia el primer día (miercoles) y se quedan un día son 14.026, debido a que este es el numero maximo de camas disponibles ese primer día. Teniendo en cuenta que solo se quedan 1 día estas personas en Italia, las camas van a estar disponibles en su totalidad el día Jueves, por este motivo el valor de personas que llegan el Jueves va a tener que ser 14.026 y así con el viernes, sabado y domingo debido a que cada día van a ir desocupando las camas. 

Por otro lado, Las personas que viajan de Italia a Francia el primer día (miercoles) y se quedan un día son 13.858, debido a que este es el numero maximo de camas disponibles ese primer día. Teniendo en cuenta que solo se quedan 1 día estas personas en Francia, las camas van a estar disponibles en su totalidad el día Jueves, por este motivo el valor de personas que llegan el Jueves va a tener que ser 13.858 y así con el viernes, sabado y domingo debido a que cada día van a ir desocupando las camas. 



# Fuentes de datos

Base de datos de oferta de camas anual 
https://ec.europa.eu/eurostat/databrowser/bookmark/4086d38b-fdd8-4311-b45e-c5095ed9b490?lang=en
